### PR TITLE
Customize Application settings from ElementX to TchapX

### LINKED ISSUE #78: Adapt App settings from ElementX to TchapX
Adapt:
- development buid flag
- bug report app id
- analytics
- map tiler url

### PR DESCRIPTION
**Pull request by NicolasBuquet**
Fix #78

### CODE REVIEW

File: ElementX/Sources/Application/AppSettings.swift [hunk 1]
```diff
@@ -235,17 +237,34 @@ final class AppSettings {
...
+    let bugReportApplicationId = "tchax-production-ios"
+    #else
     let bugReportApplicationId = "element-x-ios"
+    #endif
+    // Tchap: limit upload filesize to 10MB.
+//    let bugReportMaxUploadSize = 50 * 1024 * 1024
     /// The maximum size of the upload request. Default value is just below CloudFlare's max request size.
-    let bugReportMaxUploadSize = 50 * 1024 * 1024
-    
+    let bugReportMaxUploadSize = 10 * 1024 * 1024
```
Comment (yostyle) [inline ElementX/Sources/Application/AppSettings.swift:254]: Why did you change this value ?

**Review by yostyle — APPROVED** [review]
LGTM

just one question

File: ElementX/Sources/Application/AppSettings.swift (hunk 1 above)
Comment (NicolasBuquet) [reply ElementX/Sources/Application/AppSettings.swift:254]: I changed this value because on Tchap iOS Legacy, big bug reports (massive logs) failed to upload on homeServers. The limit was around 20MB if I recall correctly.
